name: test go run
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.16.5'
      - run: go version
      - run: go run cmd/generate-policies-file/*
      - run: go run cmd/tfiam/*
